"""empty message

Revision ID: 15064a855fc0
Revises: 5af5c90aca65
Create Date: 2022-11-11 22:27:15.564778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15064a855fc0'
down_revision = '5af5c90aca65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
